#ifndef ADC_H
#define ADC_H

#define ADC1_PORT GPIOC
#define ADC1_PIN GPIO_PIN_1
#define ADC2_PORT GPIOC
#define ADC2_PIN GPIO_PIN_3
#define ADC3_PORT GPIOC
#define ADC3_PIN GPIO_PIN_2
#define ADC4_PORT GPIOA
#define ADC4_PIN GPIO_PIN_1
#define ADC5_PORT GPIOA
#define ADC5_PIN GPIO_PIN_0
#define ADC6_PORT GPIOA
#define ADC6_PIN GPIO_PIN_3
#define ADC7_PORT GPIOA
#define ADC7_PIN GPIO_PIN_2
#define ADC8_PORT GPIOC
#define ADC8_PIN GPIO_PIN_5
#define ADC9_PORT GPIOC
#define ADC9_PIN GPIO_PIN_4
#define ADC10_PORT GPIOB
#define ADC10_PIN GPIO_PIN_1

#endif