#ifndef IO_H
#define IO_H

#define IO1_PORT GPIOE
#define IO1_PIN GPIO_PIN_4
#define IO2_PORT GPIOE
#define IO2_PIN GPIO_PIN_5
#define IO3_PORT GPIOE
#define IO3_PIN GPIO_PIN_6
#define IO4_PORT GPIOE
#define IO4_PIN GPIO_PIN_7
#define IO5_PORT GPIOE
#define IO5_PIN GPIO_PIN_8
#define IO6_PORT GPIOE
#define IO6_PIN GPIO_PIN_9
#define IO7_PORT GPIOE
#define IO7_PIN GPIO_PIN_10
#define IO8_PORT GPIOE
#define IO8_PIN GPIO_PIN_11
#define IO9_PORT GPIOE
#define IO9_PIN GPIO_PIN_12
#define IO10_PORT GPIOE
#define IO10_PIN GPIO_PIN_13
#define IO11_PORT GPIOE
#define IO11_PIN GPIO_PIN_14
#define IO12_PORT GPIOE
#define IO12_PIN GPIO_PIN_15
#define DIR_MOT1_PORT GPIOE
#define DIR_MOT1_PIN GPIO_PIN_14
#define DIR_MOT2_PORT GPIOE
#define DIR_MOT2_PIN GPIO_PIN_15

#endif