#ifndef PWM_H
#define PWM_H

#define PWM1_PORT GPIOB
#define PWM1_PIN GPIO_PIN_10
#define PWM2_PORT GPIOB
#define PWM2_PIN GPIO_PIN_11
#define PWM3_PORT GPIOB
#define PWM3_PIN GPIO_PIN_8
#define PWM4_PORT GPIOB
#define PWM4_PIN GPIO_PIN_9
#define PWM5_PORT GPIOB
#define PWM5_PIN GPIO_PIN_6
#define PWM6_PORT GPIOB
#define PWM6_PIN GPIO_PIN_7
#define PWM7_PORT GPIOB
#define PWM7_PIN GPIO_PIN_4
#define PWM8_PORT GPIOB
#define PWM8_PIN GPIO_PIN_5
#define PWM9_PORT GPIOB
#define PWM9_PIN GPIO_PIN_3
#define PWM10_PORT GIPOC
#define PWM10_PIN GPIO_PIN_8
#define PWM11_PORT GPIOC
#define PWM11_PIN GPIO_PIN_9
#define PWM_MOT1_PORT GPIOC
#define PWM_MOT1_PIN GPIO_PIN_8
#define PWM_MOT2_PORT GPIOC
#define PWM_MOT2_PIN GPIO_PIN_9

#endif
