#ifndef REGLAGES_MOULIN_H
#define REGLAGES_MOULIN_H

#define ANGLE_REPOS_MOULIN 0
#define ANGLE_PREND_POP_CORN 0
#define ANGLE_VIDE_POP_CORN 0
#define SLOW_PREND_POP_CORN 0
#define SLOW_VIDE_POP_CORN 0

#endif