#ifndef REGLAGE_SERVOS_H
#define REGLAGE_SERVOS_H

//Porte (inverser les deux valeurs ?)
#define ANGLE_OUVERTURE_PORTE 88
#define ANGLE_FERMETURE_PORTE 2

//Bras droit
#define ANGLE_CLAP_BRAS_DROIT 70
#define ANGLE_REPOS_BRAS_DROIT 166
#define ANGLE_GOBELET_LIBRE_BRAS_DROIT 100
#define ANGLE_GOBELET_COINCE_BRAS_DROIT 132

//Bras gauche
#define ANGLE_CLAP_BRAS_GAUCHE 92
#define ANGLE_REPOS_BRAS_GAUCHE 2
#define ANGLE_GOBELET_LIBRE_BRAS_GAUCHE 70
#define ANGLE_GOBELET_COINCE_BRAS_GAUCHE 40

//Moulin à popcorns
#define ANGLE_MAX_MOULIN 150
#define ANGLE_MIN_MOULIN 40

#endif 