#ifndef REGLAGE_SERVOS_H
#define REGLAGE_SERVOS_H

//Porte (inverser les deux valeurs ?)
#define ANGLE_OUVERTURE_PORTE 105
#define ANGLE_FERMETURE_PORTE 15

//Bras droit
#define ANGLE_CLAP_BRAS_DROIT 35
#define ANGLE_REPOS_BRAS_DROIT 170
#define ANGLE_GOBELET_LIBRE_BRAS_DROIT 0
#define ANGLE_GOBELET_COINCE_BRAS_DROIT 0

//Bras gauche
#define ANGLE_CLAP_BRAS_GAUCHE 150
#define ANGLE_REPOS_BRAS_GAUCHE 15
#define ANGLE_GOBELET_LIBRE_BRAS_GAUCHE 0
#define ANGLE_GOBELET_COINCE_BRAS_GAUCHE 0

//Moulin à popcorns
#define ANGLE_MAX_MOULIN 150
#define ANGLE_MIN_MOULIN 40

#endif 